<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, viewport-fit=cover"
    />
    <title>SnapInk — Customize</title>

    <!-- Fonts (optional but recommended for consistent preview) -->
    <link
      href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700;800&family=Bebas+Neue&display=swap"
      rel="stylesheet"
    />

    <!-- Tailwind built file -->
    <!-- This is generated by: npm run dev:css (watch) or npm run build:css (minified) -->
    <link rel="stylesheet" href="/style.css" />

    <meta name="description" content="Design your SnapInk strap mockup." />
    <meta name="theme-color" content="#0b0b0b" />
  </head>
  <body class="bg-neutral-950 text-neutral-100 antialiased">
    <!-- Optional site header / navigation -->
    <header class="border-b border-neutral-900/70">
      <div class="max-w-7xl mx-auto px-4 py-4 flex items-center justify-between">
        <a href="/" class="text-xl font-black tracking-tight">SnapInk</a>
        <nav class="text-sm text-neutral-300">
          <a class="hover:text-white" href="/#waitlist">Waitlist</a>
        </nav>
      </div>
    </header>

    <!-- React mount point -->
    <main id="customizer-root" class="min-h-[70vh]"></main>

    <footer class="border-t border-neutral-900/70">
      <div class="max-w-7xl mx-auto px-4 py-6 text-xs text-neutral-400">
        SnapInk™ Patent Pending • 2025
      </div>
    </footer>

    <noscript>
      <div class="max-w-3xl mx-auto p-4 text-sm text-red-300">
        JavaScript is required to use the customizer.
      </div>
    </noscript>

    <!-- Vite entry:
         - DEV: Vite will load /src/customize.tsx directly (npm run dev)
         - BUILD: Vite rewrites this in dist/customize.html to the hashed bundle in /assets
    -->
    <script type="module" src="/src/customize.tsx"></script>
  </body>
</html>
